language: ruby
bundler_args: --without tool
rvm:
  - 1.9.3
  - jruby-19mode
  - 2.1.0
  - ruby-head
  - jruby-head
  - jruby-head
  - ruby-head

# script:
#   - ruby tests/Factomd.test.rb
#   - ruby tests/FactomWalletd.test.rb
#   - ruby tests/Debug.test.rb
