language: ruby
bundler_args: --without tool
rvm:
  # - 1.9.3
  # - jruby-19mode
  - 2.3.0
  # - ruby-head
  # - jruby-head
  # - jruby-head
  # - ruby-head

before_script:
 - sudo gem update --system
 - gem install dry-types
 - gem install dry-struct

# script:
#   - ruby tests/Factomd.test.rb
#   - ruby tests/FactomWalletd.test.rb
#   - ruby tests/Debug.test.rb
